name: Sync to Hugging Face
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Action"
          
          # मिसिंग इमेज वाले एरर को इग्नोर करने की कमांड
          git config lfs.allowincompletepush true
          
          # LFS फाइलें पुश करें (|| true का मतलब है कि अगर कोई फाइल नहीं मिली, तो भी प्रोसेस आगे बढ़ेगी)
          git lfs push --all https://oauth2:$HF_TOKEN@huggingface.co/spaces/Veda-Labs/Vedika-gen-2.0-img-gen || true
          
          # आपका मेन कोड फोर्स पुश करें
          git push -f https://oauth2:$HF_TOKEN@huggingface.co/spaces/Veda-Labs/Vedika-gen-2.0-img-gen main
