name: Sync to Hugging Face
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fix LFS and Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Action"
          
          # जो इमेज फाइलें गायब हैं, उन्हें डिप्लॉयमेंट से हटा दें ताकि हगिंग फेस ब्लॉक न करे
          git rm -rf docs/images/ || true
          git commit -m "Remove missing LFS images to fix HF sync error" || true
          
          # अब आपका मुख्य कोड और फाइलें बिना किसी रुकावट के पुश हो जाएंगी
          git push -f https://oauth2:$HF_TOKEN@huggingface.co/spaces/Veda-Labs/Vedika-gen-2.0-img-gen main
